config/routes.rb
Rails.application.routes.draw do # config_bookers2
  
  devise_for :users
    # ユーザーズ
   
  root to: "homes#top"
    # ホーム
  
  get 'home/about' => "homes#about", as: 'about'
    # 取得 '実際の表示アドレス' => "指定のコントローラー#アクション", as: "名前つきルート"
  
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
    # booksディレクトリ ルーティング自動生成 onlyで(限定生成)
    
    
  resources :users, only: [:show, :index, :edit, :update]
    # users ルーティング自動生成 onlyで(限定生成)
   
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   
end

app/models/user.rb
class User < ApplicationRecord
    
       # bookers2_app_models_user
  
       # Include default devise modules. Others available are:
       # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          # パスワードの正確性
          # ユーザー登録や編集,削除
          # パスワードをリセット
          # ログイン情報を保存
          # emailのフォーマットなどのバリデーション
   
   has_many :books, dependent: :destroy
          # たくさん持っている:モデルが 1:N になるよう関連付け:削除
   
   has_one_attached :profile_image
          # profile_imageという名前でActiveStorageで
          # プロフィール画像を保存できるように設定
   
   validates :name,
    length: { minimum: 2, maximum: 20 }, uniqueness: true
          # バリデーションの設定 :　name:一意性を当てえる
    
   validates :introduction,
    length: { maximum: 50 }
          # バリデーションの設定 :
          
          
  def get_profile_image(width, height)
        # 取得_特定の名前(引数= 幅,高さ)
        # 特定の処理を名前で呼び出すことが可能
        # カラムを呼び出すようにこの処理（メソッド）を
        # 呼び出すことができる
        
    unless profile_image.attached?
        #
       file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
        # 
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        #
    end
    
    profile_image.variant(resize_to_limit: [width, height]).processed
        # 画像サイズの変換 [引数(メソッドに渡す値)= 幅,高さ]
        # 例, get_profile_image(数値, 200)
  end
             
end
   
   
   

app/controllers/users_controller.rb
class UsersController < ApplicationController
              # bookers2_app_controller_users
   
   before_action :is_matching_login_user, only: [:edit, :update]
              # "edit"と"update"のアクションの実行前に、
              # "is_matching_login_user"を実行させる記述
   
   
   def show
       
       @book = Book.new
              # インスタンス変数 = モデル名 空オブジェクト 新規作成
              # 左の箱に右を格納
              # インスタンス名はなんでもいい,空のオブジェクトもなんでもいい
         
       @user = User.find(params[:id])
              # インスタンス変数 = ユーザー_find 探す:単数でどれか一つ
              
       @books = @user.books
       
       #@post_images = @user.post_images.page(params[:page])
              # メソッド 1:N の関係性 [1] (アソシエーション)
              # .ページ送り機能
       
   end
   
   
   def index
       
       @book = Book.new
        # インスタンス変数 = モデル名 空オブジェクト 新規作成
        # 左の箱に右を格納
        # インスタンス名はなんでもいい,空のオブジェクトもなんでもいい
       
       
       @user = current_user
              # ログイン中の個人のユーザー
              
       @users = User.all
   
   end
   
   
   def edit
       
       is_matching_login_user
       
       @user = User.find(params[:id])
              # URLを参考に特定のidを持ったレコードを取得する
       
       @book_image = Book.new
              # 
       
   end
   
   
   def update
       
       is_matching_login_user
       
       @user = User.find(params[:id])
              # インスタンス変数 = ユーザー_find 探す:単数でどれか一つ
              # レコードを一つ取得？
       
       if  @user.update(user_params)
              # ユーザーのアップデート
           
           flash[:notice] = "You have updated user successfully."
              # flash[:notice] は 投稿が成功した時だけ
              # エラーメッセージでは使わない
           
           redirect_to user_path(@user.id)
              # インスタンス変数 = ユーザー_find 探す:単数でどれか一つ  user_path(@user.id)
              # 遷移先 '/books'? user_path(@user.id)
       else
           
           render :edit
              # アクションを実行しない
       end
   end
   
   
   private
   
   
   def user_params
              # 
              
      params.require(:user).permit(:name, :profile_image, :introduction)
              # require :モデル名
              # permit  :userの書き込みを許可してあげる？
              # params.require(:モデル名).
              # permit(:保存を許可するカラム指定)
   end
    
    
   def is_matching_login_user
              # ログインしているユーザーのidとURLに含まれるidを比較し、
              # 一致しなければ投稿画像一覧ページに移動する処理
          
       user = User.find(params[:id])
              # ローカル変数 = ユーザー_find 探す:単数でどれか一つ
              # URLを参考に特定のidを持ったレコードを取得する
          
       unless user.id == current_user.id
              # ログイン中,ユーザーid,取得
          
       redirect_to user_path(current_user)
              # 遷移先 Books#index 投稿画像一覧へ
          
       end
   end
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<!-- booksers2_users_部分テンプレート_完了-->

<!-- ここから -->

  <!-- フラッシュメッセージ投稿成功時 -->
  <div>
    <%= flash[:notice] %>
  </div>
  

  <h2>User info</h2>
            <!-- image -->
    <%= image_tag user.get_profile_image(100,100) %>
            <!-- name introduction -->
          <table class="table">
            <tbody>
              <tr></tr>
                <!-- name -->
              <tr>
                <th>name</th>
                <th><%= user.name %></th>
              </tr>
                <!-- introduction -->
              <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
              </tr>
            </tbody>
          </table>
          
            <!-- User info_遷移先がしっかり更新先になった_チェックボックス -->
          <div class="row">
            
              <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
                <i class="fas fa-user-cog" aria-hidden="true"></i>
              <% end %>
            
          </div>
            <h2 class="mt-3">New book</h2>
                
                <!-- new book_title_opinion_create book -->
              <%= form_with model: Book.new do |f| %>
                  <!-- title box -->
                <div class="form-group">
                  <label for="book_title">Title</label><br>
                    <%= f.text_field :title %>
                </div>
                  <!-- Opinion box-->
                <div class="form-group">
                  <label for="book_opinion">Opinion</label><br>
                    <%= f.text_area :body %>
                </div>
                  <!-- Create Book box -->
                <div class="form-group">
                  <%= f.submit 'Create Book',class:"btn btn-success" %>
                </div>
              <% end %>


<!-- ここまで -->

app/views/users/edit.html.erb
  <!-- Users_edit_編集_#top_bookers2_users_edit_完了 -->
  
<main>
  <p id="notice"></p>
  
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
            <!-- エラーメッセージ user info -->
          <% if @user.errors.any? %>
            <h2>
              <%= @user.errors.count %>error prohibited this obj from being saved:
            </h2>
            
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul> 
          <% end %>
          
        <%= form_with model: @user do |f| %>
            <!-- name_box -->
          <div class="form-group">
            <label for="user_name">
              Name
            </label>
              <%= f.text_field :name, class:"form-control" %>
          </div>
            <!-- Image_box -->      
          <div class="form-group">
            <label for="user_image">
              Image
            </label>
              <%= f.file_field :profile_image, accept: "image/*", class: "w-100" %>
          </div>
            <!-- Introduction_box -->      
          <div class="form-group">
            <label for="user_introduction">
              Introduction
            </label>
              <%= f.text_area :introduction, class:"form-control", rows:"3" %>
          </div>
            <!-- Update_User_チェックボックス -->
          <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-lg btn-secondary btn- mt-4" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
  <!-- Users_一覧_#index_top_bookers2_views_users_index_完了-->
  <!-- ユーザーの投稿一覧 -->
<html>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
        <!-- 部分テンプレートrender表記 -->
      <div class="col-md-3">
        <%= render 'users/list', user: @user,book: @book %>
      </div>
      
      <div class="col-md-8 offset-md-1">
        <h1>Users</h1>
        
        <table class="table table-hover table-inverse">
            <!-- image_name -->
          <thead>
            <tr>
              <th>image</th>
              <th></th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
            <!-- User 一覧 -->
          <tbody>
            <% @users.each do |user| %>
                <!-- user_画像_name_link -->
              <tr align="center">
                  <!-- user_画像 -->
                <td>
                  <%= image_tag user.get_profile_image(100,100) %>
                </td>
                  <td></td>
                  <!-- user_name -->
                <td>
                  <%= user.name %>
                </td>
                  <!-- show_link -->
                <td>
                  <%= link_to "Show",user_path(user.id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
            
        </table>
        
      </div>
    </div>
  </div>
</html>

app/views/users/show.html.erb
<!-- bookers2_users_show_top_完了 -->

<!-- ユーザー詳細_部分テンプレート -->

<!-- 部分テンプレートrender表記 -->
<main>
  <p id="notice"></p>
  
  <div class="container px-5 px-sm-0">
    <div class="row">
        <!-- 部分テンプレート -->
      <div class="col-md-3">
        <%= render 'users/list', user: @user,book: @book %>
      </div>
        <!-- Book 画像投稿一覧 -->
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        
        <table class="table table-hover table-inverse">
            <!-- title opinion -->
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          
          <tbody>
            <% @books.each do |book| %>
                <!-- Bookscontroller_index_@books_listsに投稿されたブックデータが入ってる -->
                <!-- .each(繰り返し処理) -->
                <!-- @books_listsを |book| に格納する -->
              <tr align=”center”>
                <td><%= link_to image_tag book.user.get_profile_image(100,100) %></td>
                  <!-- image_tag(画像表示する時の表記) 上記で格納された|book|から.userデータを取り出す.get_profile_image(100,100) -->
                <td><%= link_to book.title, book_path(book.id) %></td>
                  <!-- userの詳細ページに遷移 -->
                <td><%= book.body %></td>
              </tr>
　          <% end %>
          </tbody>
          
        </table>
      </div>
    </div>
  </div>
</main>