config/routes.rb
Rails.application.routes.draw do # config_bookers2
  
  devise_for :users
    # ユーザーズ
   
  root to: "homes#top"
    # ホーム
  
  get 'home/about' => "homes#about", as: 'about'
    # 取得 '実際の表示アドレス' => "指定のコントローラー#アクション", as: "名前つきルート"
  
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
    # booksディレクトリ ルーティング自動生成 onlyで(限定生成)
    
    
  resources :users, only: [:show, :index, :edit, :update]
    # users ルーティング自動生成 onlyで(限定生成)
   
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
  <!-- bookers2_layouts全ページ共通_application -->
  
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/5e22f18747.js" crossorigin="anonymous"></script>
      <!-- FontAwesomeの記述 -->
      
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <!-- 変更後 -->
      <!-- stylesheet_link_tagは、app/assets 配下のファイルを cssが -->
      <!-- stylesheet_pack_tagは、app/javascript 配下のファイルを参照する -->
      
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!--  -->
      
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
           <!-- navbar濃いグレー? -->
        <div class="container">
              <!-- Bookers -->
            <a class="navbar-brand" href="/">
              <span>Bookers</span>
            </a>
            
            <button class="navbar-toggler" 
            type="button" data-toggle="collapse" 
            data-target="#navbarNavDropdown" 
            aria-controls="navbarNavDropdown" 
            aria-expanded="true" 
            aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
                <!-- ログイン_ログアウト -->
              <ul class="navbar-nav ml-auto">
                  <!-- ログイン_状態 -->
                <% if user_signed_in? %>
                    <!-- Home -->
                  <li>
                    <%= link_to user_path(current_user.id),class: 'nav-link text-light' do %>
                      <i class="fas fa-home" aria-hidden="true"></i>
                        <!-- ログイン中のユーザーのid : current_user.id -->
                      Home
                    <% end %>
                  </li>
                    <!-- Users一覧へ -->
                  <li>
                    <%= link_to users_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-users" aria-hidden="true"></i>
                        Users<!--  -->
                    <% end %>
                  </li>
                    <!-- Books一覧へ -->
                  <li>
                    <%= link_to books_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-book-open" aria-hidden="true"></i>
                        Books<!--  -->
                    <% end %>
                  </li>
                    <!-- ログアウト -->
                  <li>
                    <%= link_to destroy_user_session_path,class: 'nav-link text-light',method: :delete do %>
                      <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                        Log out<!-- 本のアイコン -->
                    <% end %>
                  </li>
                  
                  <!-- ログアウト_状態 -->
                <% else %>
                    <!-- Home〇 -->
                  <li>
                    <%= link_to root_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-home" aria-hidden="true"></i>
                        Home<!-- -->
                    <% end %>
                  </li>
                    <!-- About〇 -->
                  <li>
                    <%= link_to about_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-link" aria-hidden="true"></i>
                        About<!--  -->
                    <% end %>
                  </li>
                    <!-- Sign up〇 -->
                  <li>
                    <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-user-plus" aria-hidden="true"></i>
                        Sign up<!--  -->
                    <% end %>
                  </li>
                    <!-- ログイン -->
                  <li>
                    <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
                      <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                        Log in<!-- -->
                    <% end %>
                  </li>
                  
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
      <%= yield %>
      
      <!-- CopyRight Infratop.inc -->
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>
              <font style="vertical-align: inherit;">
                 CopyRight Infratop.inc
              </font>
            </p>
          </div>
        </div>  
      </div>
    </footer>
    
  </body>
</html>